import React from 'react';
import styles from './styles/About.module.css';

const AboutPage = () =>{

    return(
        <div className={styles['about-container']}>
            <h1>Ailuminate The AI Literacy and Awareness Platform</h1>
            <h2>About us</h2>

            <div className={styles['about-card']}>
                {/* This text is generated by ChatGPT based on the assignment text */}
                <p>Welcome to the about page for Ailuminate.</p>
                <p>The perfect platform for AI literacy and awareness!</p>
                <p>Ailuminate is a dynamic, interactive platform designed to enhance AI literacy through 
                    engaging, quiz-based experiences. Built by students of the IDG2100 Full-Stack 
                    Web Development course at NTNU, Ailuminate bridges the gap between education and 
                    technology by helping users distinguish between human- and AI-generated content 
                    across text, images, music, and more.</p>
                <p>This full-stack web application supports three user roles—Visitors, Researchers, 
                    and Admins—each with tailored experiences and responsibilities. 
                    Visitors can freely explore and take quizzes, receive personalized feedback, 
                    and gain insights into AI content generation. Researchers can create and manage quizzes, 
                    analyze user responses, and extract valuable educational data. Admins maintain the platform, 
                    overseeing user management and usage analytics.</p>
                <p>Ailuminate is more than a quiz tool—it's an educational initiative. 
                    Backed by NTNU’s Department of Design, it is developed using modern technologies 
                    including the MERN stack (MongoDB, Express, React, Node.js), with secure authentication, 
                    responsive design for mobile and museum displays, and thorough documentation using Swagger 
                    and Storybook.</p>
                <p>By combining engaging content, academic rigor, and practical development skills, 
                    Ailuminate serves as both a learning tool and a showcase of full-stack web development in action.</p>
            </div>
        </div>
    );
};

export default AboutPage;